In [1]:
# reding one csv file 
# optional:load data from URL 
#(if connection works) 
import pandas as pd
df_premier21=pd.read_csv("E0.csv")
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,E0,21/03/2026,17:30,Everton,Chelsea,3,0,H,1,0,...,1.88,1.98,NaN,NaN,2.15,1.98,1.98,1.82,1.96,2.03
305,E0,21/03/2026,20:00,Leeds,Brentford,0,0,D,0,0,...,2.05,1.80,NaN,NaN,2.12,1.83,2.04,1.76,2.12,1.87
306,E0,22/03/2026,12:00,Newcastle,Sunderland,1,2,A,1,0,...,1.93,1.93,NaN,NaN,2.18,1.96,1.95,1.84,1.99,2.00
307,E0,22/03/2026,14:15,Aston Villa,West Ham,2,0,H,1,0,...,2.00,1.85,NaN,NaN,2.00,1.90,1.93,1.84,2.04,1.95
308,E0,22/03/2026,14:15,Tottenham,Nott'm Forest,0,3,A,0,1,...,2.03,1.83,NaN,NaN,2.12,1.83,2.04,1.76,2.13,1.87

In [2]:
# rename some columns
df_premier21.rename(columns={'FTHG':'home_goals',
                             'FTAG':'away_goals'}, inplace=True)

df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,E0,21/03/2026,17:30,Everton,Chelsea,3,0,H,1,0,...,1.88,1.98,NaN,NaN,2.15,1.98,1.98,1.82,1.96,2.03
305,E0,21/03/2026,20:00,Leeds,Brentford,0,0,D,0,0,...,2.05,1.80,NaN,NaN,2.12,1.83,2.04,1.76,2.12,1.87
306,E0,22/03/2026,12:00,Newcastle,Sunderland,1,2,A,1,0,...,1.93,1.93,NaN,NaN,2.18,1.96,1.95,1.84,1.99,2.00
307,E0,22/03/2026,14:15,Aston Villa,West Ham,2,0,H,1,0,...,2.00,1.85,NaN,NaN,2.00,1.90,1.93,1.84,2.04,1.95
308,E0,22/03/2026,14:15,Tottenham,Nott'm Forest,0,3,A,0,1,...,2.03,1.83,NaN,NaN,2.12,1.83,2.04,1.76,2.13,1.87

In [3]:

# loop through range of season
# reading multiple csv files from URLs
# optional:load data from URL 
#(if connection works)
# for season 2024/2025
import pandas as pd

files = [
     "E0.csv",
     "E1.csv",
     "E2.csv",
     "E3.csv"
]

dfs = []

for file in files:
    temp = pd.read_csv(file)
    dfs.append(temp)

df_season1 = pd.concat(dfs, ignore_index=True)

print(df_season1.head())

  Div        Date   Time     HomeTeam     AwayTeam  FTHG  FTAG FTR  HTHG  \
0  E0  15/08/2025  20:00    Liverpool  Bournemouth     4     2   H     1
1  E0  16/08/2025  12:30  Aston Villa    Newcastle     0     0   D     0
2  E0  16/08/2025  15:00     Brighton       Fulham     1     1   D     0
3  E0  16/08/2025  15:00   Sunderland     West Ham     3     0   H     0
4  E0  16/08/2025  15:00    Tottenham      Burnley     3     0   H     1

   HTAG  ... B365CAHA PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA  \
0     0  ...     1.78  2.07   1.85     2.03     1.88     1.94     1.76
1     0  ...     1.80  2.02   1.89     2.06     1.80     1.95     1.74
2     0  ...     2.03  1.93   2.00     1.84     2.03     1.80     1.96
3     0  ...     1.90  1.97   1.95     1.95     1.94     1.86     1.78
4     0  ...     1.88  1.99   1.93     1.98     1.91     1.88     1.83

   BFECAHH  BFECAHA  Unnamed: 132
0     2.14     1.86           NaN
1     2.14     1.86           NaN
2     1.91     2.08           NaN
3     2.02     1.97           NaN
4     2.07     1.92           NaN

[5 rows x 133 columns]

In [5]:
# len frames
len(df_season1)

1783

In [19]:

# loop through range of season
# reading multiple csv files from URLs
# optional:load data from URL 
#(if connection works)
# for season 2023/2024
import pandas as pd

files = [
       "E0 (4).csv",
       "E1 (2).csv",
       "E2 (2).csv",
       "E3 (2).csv"
]

dfs = []

for file in files:
    temp = pd.read_csv(file)
    dfs.append(temp)

df_season2 = pd.concat(dfs, ignore_index=True)

print(df_season2.head())

  Div        Date   Time    HomeTeam     AwayTeam  FTHG  FTAG FTR  HTHG  HTAG  \
0  E0  16/08/2024  20:00  Man United       Fulham     1     0   H     0     0
1  E0  17/08/2024  12:30     Ipswich    Liverpool     0     2   A     0     0
2  E0  17/08/2024  15:00     Arsenal       Wolves     2     0   H     1     0
3  E0  17/08/2024  15:00     Everton     Brighton     0     3   A     0     1
4  E0  17/08/2024  15:00   Newcastle  Southampton     1     0   H     1     0

   ... B365CAHH B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA  \
0  ...     1.86     2.07   1.83   2.11     1.88     2.11     1.82     2.05
1  ...     2.05     1.88   2.04   1.90     2.20     2.00     1.99     1.88
2  ...     2.02     1.91   2.00   1.90     2.05     1.93     1.99     1.87
3  ...     1.87     2.06   1.86   2.07     1.92     2.10     1.83     2.04
4  ...     1.87     2.06   1.88   2.06     1.89     2.10     1.82     2.05

   BFECAHH  BFECAHA
0     1.90     2.08
1     2.04     1.93
2     2.02     1.96
3     1.88     2.11
4     1.89     2.10

[5 rows x 120 columns]

In [18]:

# loop through range of season
# reading multiple csv files from URLs
# optional:load data from URL 
#(if connection works)
# for season 2022/2023
import pandas as pd

files = [
       "E0 (5).csv",
       "E1 (3).csv",
       "E2 (4).csv",
       "E3 (3).csv"
]

dfs = []

for file in files:
    temp = pd.read_csv(file)
    dfs.append(temp)

df_season3 = pd.concat(dfs, ignore_index=True)

print(df_season3.head())

  Div        Date   Time     HomeTeam       AwayTeam  FTHG  FTAG FTR  HTHG  \
0  E0  11/08/2023  20:00      Burnley       Man City     0     3   A     0
1  E0  12/08/2023  12:30      Arsenal  Nott'm Forest     2     1   H     2
2  E0  12/08/2023  15:00  Bournemouth       West Ham     1     1   D     0
3  E0  12/08/2023  15:00     Brighton          Luton     4     1   H     1
4  E0  12/08/2023  15:00      Everton         Fulham     0     1   A     0

   HTAG  ... AvgC<2.5  AHCh  B365CAHH  B365CAHA  PCAHH  PCAHA  MaxCAHH  \
0     2  ...     2.28  1.50      1.95      1.98   1.95   1.97      NaN
1     0  ...     2.63 -2.00      1.95      1.98   1.93   1.97     2.01
2     0  ...     2.12  0.00      2.02      1.91   2.01   1.92     2.06
3     0  ...     2.48 -1.75      2.01      1.92   2.00   1.91     2.14
4     0  ...     1.71 -0.25      2.06      1.87   2.04   1.88     2.08

   MaxCAHA  AvgCAHH  AvgCAHA
0      NaN     1.92     1.95
1     2.09     1.95     1.92
2     1.96     1.96     1.91
3     1.93     2.00     1.86
4     1.99     1.98     1.88

[5 rows x 106 columns]

In [23]:
# organize all data in dictionary 
#create a dictionary with original name of league as key
dict_countries = {
    "Spanish La Liga"          : 'SP1',
    "Spanish Segunda Division" : 'SP2',
    "German Bundes Liga"       : 'D1',
    "English Premier Liga"     : 'E0',
    "English League 1"         : 'E2',
    "English League 2"         : 'E3'     
}
#get a dictionary element 
dict_countries['Spanish La Liga']

'SP1'

In [24]:
# concat all 3 seasons together 
df_all = pd.concat([df_season1, df_season2, df_season3], ignore_index=True, sort=False)
df_all

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,IWA,VCH,VCD,VCA,IWCH,IWCD,IWCA,VCCH,VCCD,VCCA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5850,E3,27/04/2024,15:00,Gillingham,Doncaster,2,2,D,0,2,...,NaN,3.60,3.7,1.95,NaN,NaN,NaN,2.88,3.60,2.30
5851,E3,27/04/2024,15:00,Milton Keynes Dons,Sutton,4,4,D,2,0,...,NaN,2.15,3.9,3.00,NaN,NaN,NaN,2.05,3.90,3.13
5852,E3,27/04/2024,15:00,Salford,Harrogate,2,2,D,2,2,...,NaN,1.73,3.9,4.50,NaN,NaN,NaN,1.73,4.20,4.10
5853,E3,27/04/2024,15:00,Swindon,Morecambe,3,3,D,2,2,...,NaN,1.83,4.0,3.80,NaN,NaN,NaN,1.50,4.80,5.50
5854,E3,27/04/2024,15:00,Wrexham,Stockport,2,1,H,0,1,...,NaN,2.38,3.7,2.70,NaN,NaN,NaN,2.20,3.75,3.00

In [41]:
# organize all data in dictionary 
#create a dictionary with original name of league as key
dict_countries = {
    "Spanish La Liga"          : 'SP1',
    "Spanish Segunda Division" : 'SP2',
    "German Bundes Liga"       : 'D1',
    "English Premier Liga"     : 'E0',
    "English League 1"         : 'E2',
    "English League 2"         : 'E3'     
}
df_all = pd.concat([df_season1, df_season2, df_season3], ignore_index=True, sort=False)
df_all

dict_historical_data = {}


leagues = df_all['Div'].unique()


for league in leagues:
    
    dict_historical_data[league] = df_all[df_all['Div'] == league]

dict_historical_data['E0']

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,IWA,VCH,VCD,VCA,IWCH,IWCD,IWCA,VCCH,VCCD,VCCA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4194,E0,19/05/2024,16:00,Crystal Palace,Aston Villa,5,0,H,2,0,...,NaN,1.80,4.00,3.7,NaN,NaN,NaN,1.60,4.4,5.00
4195,E0,19/05/2024,16:00,Liverpool,Wolves,2,0,H,2,0,...,NaN,1.13,8.00,15.0,NaN,NaN,NaN,1.11,10.5,19.00
4196,E0,19/05/2024,16:00,Luton,Fulham,2,4,A,1,2,...,NaN,2.88,3.75,2.2,NaN,NaN,NaN,3.10,3.8,2.15
4197,E0,19/05/2024,16:00,Man City,West Ham,3,1,H,2,1,...,NaN,1.07,10.50,22.0,NaN,NaN,NaN,1.06,15.0,26.00
4198,E0,19/05/2024,16:00,Sheffield United,Tottenham,0,3,A,0,1,...,NaN,7.50,5.75,1.3,NaN,NaN,NaN,9.00,6.0,1.30

In [1]:
import os
print(os.getcwd())

/home/6205c32e-4d00-4e63-bdea-c9ffa8fe7d75